/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'DSA',
      link: {
        type: 'generated-index',
        title: 'DSA Notes',
        description: 'Data Structures and Algorithms notes and handbook.',
        slug: '/dsa',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'C++ STL Handbook',
          items: [{type: 'autogenerated', dirName: 'DSA/STL'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Web Development',
      link: {
        type: 'generated-index',
        title: 'Web Development',
        description: 'Notes on React, TypeScript, and modern web technologies.',
        slug: '/web-dev',
      },
      items: [{type: 'autogenerated', dirName: 'WebDev'}],
    },
  ],
};

export default sidebars;
