/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'DSA (C++)',
      link: {
        type: 'generated-index',
        title: 'DSA Knowledge Base',
        description: 'Data Structures and Algorithms Knowledge Base and handbook.',
        slug: '/dsa',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Basics',
          link: {
            type: 'generated-index',
            title: 'DSA Basics',
            description: 'Foundational concepts of Data Structures and Algorithms.',
            slug: '/dsa/basics',
          },
          items: [
            {
              type: 'category',
              label: 'Bit Manipulation',
              items: [{type: 'autogenerated', dirName: 'dsa/basics/bit-manipulation'}],
            },
            {
              type: 'category',
              label: 'C++ Fundamentals',
              items: [{type: 'autogenerated', dirName: 'dsa/basics/cpp-fundamentals'}],
            },
            {
              type: 'category',
              label: 'Pointers',
              items: [{type: 'autogenerated', dirName: 'dsa/basics/pointers'}],
            },
            {
              type: 'category',
              label: 'C++ STL',
              items: [{type: 'autogenerated', dirName: 'dsa/basics/stl'}],
            },
            {
              type: 'category',
              label: 'Hashing',
              items: [
                {
                  type: 'category',
                  label: 'Hashing Fundamentals',
                  items: [{type: 'autogenerated', dirName: 'dsa/basics/hashing/hashing fundamentals'}],
                },
                {
                  type: 'category',
                  label: 'map',
                  items: [{type: 'autogenerated', dirName: 'dsa/basics/hashing/map'}],
                },
                {
                  type: 'category',
                  label: 'unordered_map',
                  items: [{type: 'autogenerated', dirName: 'dsa/basics/hashing/unordered_map'}],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Web Development',
      link: {
        type: 'generated-index',
        title: 'Web Development',
        description: 'Knowledge Base on React, TypeScript, and modern web technologies.',
        slug: '/web-dev',
      },
      items: [{type: 'autogenerated', dirName: 'web-dev'}],
    },
  ],
};

export default sidebars;
