/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'DSA (C++)',
      link: {
        type: 'generated-index',
        title: 'DSA Knowledge Base',
        description: 'Data Structures and Algorithms Knowledge Base and handbook.',
        slug: '/dsa',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Basics',
          link: {
            type: 'generated-index',
            title: 'DSA Basics',
            description: 'Foundational concepts of Data Structures and Algorithms.',
            slug: '/dsa/basics',
          },
          items: [
            {
              type: 'category',
              label: 'C++ Fundamentals',
              items: [{type: 'autogenerated', dirName: 'DSA/Basics/C++ Fundamentals'}],
            },
            {
              type: 'category',
              label: 'Datatypes',
              items: [{type: 'autogenerated', dirName: 'DSA/Basics/Datatypes'}],
            },
            {
              type: 'category',
              label: 'Pointers',
              items: [{type: 'autogenerated', dirName: 'DSA/Basics/Pointers'}],
            },
            {
              type: 'category',
              label: 'C++ STL',
              items: [{type: 'autogenerated', dirName: 'DSA/Basics/STL'}],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Web Development',
      link: {
        type: 'generated-index',
        title: 'Web Development',
        description: 'Knowledge Base on React, TypeScript, and modern web technologies.',
        slug: '/web-dev',
      },
      items: [{type: 'autogenerated', dirName: 'WebDev'}],
    },
  ],
};

export default sidebars;
